env.CI = 'false'
pipeline {
    agent any
    stages {
        stage('Deployment') {
            steps {
                 bat 'C:\\Jenkins\\BatchFiles\\Kill_Process.bat 3000'
               // bat 'D:\\Jenkins\\BatchFiles\\Kill_Process.bat 3000'
                bat 'npm install --force'
                bat 'npm run build --configuration=production'
                script {
                    def jobName = env.JOB_NAME
                    def packageJson = readJSON file: 'package.json'
                    def appName = packageJson.name
                    // timeout(time: 2, unit: 'MINUTES') {
                         bat "\"C:\\Jenkins\\BatchFiles\\Deploy_React.bat\" ${jobName} ${appName}"
                        //bat "D:\\Jenkins\\BatchFiles\\Deploy_React.bat\" ${jobName} ${appName}"
                    // }
                }
            }
        }
    }
}