server:
 port: 5000 

spring: 
  application:
    name: GatewayMS
  cloud:
    consul:
      host: localhost
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
#        TODO
        - id: CartMS
          uri: http://localhost:5001/
          predicates:
            - Path=/cart-api/**
            
        - id: CustomerMS
          uri: http://localhost:5002/
          predicates:
            - Path=/customer-api/**

        - id: MedicineMS
          uri: http://localhost:5003/
          predicates:
            - Path=/medicine-api/**

        - id: OrderMS
          uri: http://localhost:5004/
          predicates:
            - Path=/order-api/**

        - id: PaymentMS
          uri: http://localhost:5005/
          predicates:
            - Path=/payment-api/**